# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Unicode-MapUTF8
version:      1.10
version_from: lib/Unicode/MapUTF8.pm
installdirs:  site
requires:
    Jcode:                         0
    Unicode::Map:                  0
    Unicode::Map8:                 0
    Unicode::String:               0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
